name: Github CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Build
        run: |
          yarn
          yarn build
      - name: Push to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ucandoit/nobot-front
          tags: 1.0.0
      